@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

    Joueur *--> "1 \n m_terrainPrive" Terrain : belongs to >
    Joueur *-> "1 \n m_piochePrive" Pioche : belongs to >

    Joueur o-> "getTerrain" Terrain
    Joueur o-up-> "getPioche" Pioche

@enduml