@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class JeuPP{
    + {static} main(args[] : String)
}

package Jeu
{
    class JeuPokemon
    {

        + lancerJeu()

        + afficheJeu(tour : Tour ,adversaire: Adversaire, utilisateur: Utilisateur)
        + afficheTourJoueur(tour : Tour, utilisateur : Utilisateur)
        + afficheTourAdversaire(tour : Tour , adversaire : Adversaire)

        + verifTourUtilisateur(tour : Tour, utilisateur : Utilisateur)
        + verifTourAdversaire(tour : Tour , adversaire : Adversaire)
        + initTerrain(Utilisateur : utilisateur)
    }

        class AffichageJeu()
        class AffichageTourJoueur;
        class





    }

@enduml